trigger:
  branches:
    include:
      - "master"
  tags:
    include:
      - "v*"

# PR build config is manually overridden in Azure pipelines UI with different secrets
pr: none

jobs:
  - job: release
    displayName: "Linux-ARM release.server_only"
    pool: "ARM for Envoy"
    steps:
      - template: bazel.yml
        parameters:
          ciTarget: bazel.release.server_only
          rbe: ""
          bazelBuildExtraOptions: "--curses=no"
